### ISSUE TITLE
type.rb:23-26: Right now only Score and Http classes have...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold#394]
The puzzle `98-a72851ba` from #98 has to be resolved:

https://github.com/zold-io/zold/blob/cdb06a0b8a2f2814c2aa933756e5db4c2d7063ab/lib/zold/type.rb#L23-L26

The puzzle was created by Emiliano Della Casa on 12-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#394](https://github.com/zold-io/zold/issues/394) is now in scope, role is `DEV`

**Comment by emilianodellacasa** [comment]
@yegor256 Please assign this issue to me, to keep on working on the refactoring

**Comment by yegor256** [comment]
@0crat assign @emilianodellacasa

**Comment by 0crat** [comment]
> @0crat assign @emilianodellacasa  ([here](https://github.com/zold-io/zold/issues/394#issuecomment-405934351))

@yegor256 The job [#394](https://github.com/zold-io/zold/issues/394) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/1991351085); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by emilianodellacasa** [comment]
This issue has been solved in PR #416 and #417

**Comment by emilianodellacasa** [comment]
@yegor256 The old puzzle is gone, so as soon as you merge #417 this issue will be closed

**Comment by 0pdd** [comment]
The puzzle `98-a72851ba` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#421](https://github.com/zold-io/zold/issues/421) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#394](https://github.com/zold-io/zold/issues/394) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#421](https://github.com/zold-io/zold/issues/421) is solved here.
